# Generated by Django 4.0.6 on 2022-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_description_article_price_sefaresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sefaresh',
            name='discription',
        ),
        migrations.AddField(
            model_name='article',
            name='discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
