# Generated by Django 4.0.6 on 2022-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_sefaresh_discription_article_discription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='item',
        ),
        migrations.AddField(
            model_name='sefaresh',
            name='Number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
