# Generated by Django 4.0.6 on 2022-07-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_title_article_item_sefaresh_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sefaresh',
            old_name='Number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='sefaresh',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
